/**
 * End-to-end test for SignalCraft Stage 1 + Stage 3 (#03 Sentiment).
 *
 * Registers a deterministic test provider on the "mock-1" model that
 * returns valid SentimentSchema JSON, then runs the pipeline against a
 * fresh signalcraft_jobs row using Hacker News as the upstream collector.
 *
 * Run:
 *   DATABASE_URL=... pnpm --filter @eduright/api exec tsx src/cli/test-sentiment.ts [keyword]
 */
import { runPipeline } from "../signalcraft/pipeline.ts";
import { registerProvider } from "../llm/client.ts";
import { sentimentModuleConfig } from "../llm/modules/sentiment.ts";
import { getPool, closePool } from "../infra/db.ts";
import type { LLMProvider, LLMRequest, LLMResponse } from "../llm/types.ts";

const TENANT = "00000000-0000-0000-0000-0000000000bb";
const KEYWORD = process.argv[2] ?? "children's books";

// Test provider registered on the same name as the module's pricing
// entry. We point sentimentModuleConfig at "mock-1" for this test so the
// real Anthropic SDK is never invoked.
sentimentModuleConfig.model = "mock-1";

const cannedJson = JSON.stringify({
  sentimentRatio: { positive: 0.55, negative: 0.2, neutral: 0.25 },
  topKeywords: [
    { term: "kafka", count: 12, sentiment: "positive" },
    { term: "kids", count: 9, sentiment: "neutral" },
    { term: "education", count: 6, sentiment: "positive" },
    { term: "book", count: 5, sentiment: "neutral" },
    { term: "complex", count: 3, sentiment: "negative" },
  ],
  frameCompetition: [
    { label: "교육 vs 단순 동화", share: 0.6 },
    { label: "기술 친화 vs 추상 위험", share: 0.4 },
  ],
  confidence: "medium",
  disclaimer: "Test fixture — generated by registerProvider, not by an LLM.",
});

const testProvider: LLMProvider = {
  name: "mock",
  async call(req: LLMRequest): Promise<LLMResponse> {
    const inputChars = req.messages.reduce((s, m) => s + m.content.length, 0);
    return {
      content: cannedJson,
      inputTokens: Math.ceil(inputChars / 4),
      outputTokens: Math.ceil(cannedJson.length / 4),
      cachedInputTokens: 0,
      stopReason: "end_turn",
      latencyMs: 8,
    };
  },
};
registerProvider(testProvider);

const pool = getPool();

const insert = await pool.query<{ id: string }>(
  `INSERT INTO signalcraft_jobs
     (tenant_id, keyword, regions, modules_requested, status, current_stage)
   VALUES ($1, $2, $3, $4, 'queued', 'stage1:queued')
   RETURNING id`,
  [TENANT, KEYWORD, [], ["#03"]],
);
const jobId = insert.rows[0]?.id;
if (!jobId) throw new Error("failed to create signalcraft_jobs row");
console.log("created signalcraft job:", jobId);

const result = await runPipeline({
  jobId,
  tenantId: TENANT,
  keyword: KEYWORD,
  regions: [],
});
console.log("pipeline result:", result);

const job = await pool.query(
  `SELECT status, current_stage, progress_pct, started_at, finished_at
     FROM signalcraft_jobs
    WHERE id = $1`,
  [jobId],
);
console.log("final job row:", job.rows[0]);

const out = await pool.query(
  `SELECT module_id, status, attempts, duration_ms, model_name,
          output->'sentimentRatio' AS sentiment_ratio,
          jsonb_array_length(output->'topKeywords') AS keyword_count
     FROM signalcraft_module_outputs
    WHERE job_id = $1`,
  [jobId],
);
console.log("module outputs:", out.rows);

const usage = await pool.query(
  `SELECT model_name, module_id, input_tokens, output_tokens, cost_usd
     FROM llm_usage
    WHERE job_id = $1`,
  [jobId],
);
console.log("llm_usage rows:", usage.rows);

// Cleanup
await pool.query("DELETE FROM signalcraft_jobs WHERE id = $1", [jobId]);
await pool.query("DELETE FROM llm_usage WHERE tenant_id = $1", [TENANT]);
await closePool();
console.log("DONE");
