/**
 * Full pipeline → integrated report end-to-end test.
 *
 * Registers a fixture provider that dispatches canned JSON for all
 * 4 modules (#01, #03, #08, #13). After runPipeline completes, fetches
 * the generated reports row and prints both the JSON shape and the
 * server-rendered HTML headline.
 *
 * Run:
 *   DATABASE_URL=... pnpm --filter @eduright/api exec tsx src/cli/test-report.ts [keyword]
 */
import { runPipeline } from "../signalcraft/pipeline.ts";
import { registerProvider } from "../llm/client.ts";
import { sentimentModuleConfig } from "../llm/modules/sentiment.ts";
import { macroViewModuleConfig } from "../llm/modules/macro-view.ts";
import { summaryModuleConfig } from "../llm/modules/summary.ts";
import { integratedModuleConfig } from "../llm/modules/integrated.ts";
import { renderReportHtml, type ReportRow } from "../reports/render-html.ts";
import { getPool, closePool } from "../infra/db.ts";
import type { LLMProvider, LLMRequest, LLMResponse } from "../llm/types.ts";

const TENANT = "00000000-0000-0000-0000-0000000000dd";
const KEYWORD = process.argv[2] ?? "children's books";

sentimentModuleConfig.model = "mock-1";
macroViewModuleConfig.model = "mock-1";
summaryModuleConfig.model = "mock-1";
integratedModuleConfig.model = "mock-1";

const FIXTURES: Record<string, string> = {
  SentimentSchema: JSON.stringify({
    sentimentRatio: { positive: 0.55, negative: 0.2, neutral: 0.25 },
    topKeywords: [
      { term: "kafka", count: 12, sentiment: "positive" },
      { term: "kids", count: 9, sentiment: "neutral" },
      { term: "education", count: 6, sentiment: "positive" },
    ],
    frameCompetition: [
      { label: "education vs entertainment", share: 0.6 },
      { label: "tech-friendly vs abstract risk", share: 0.4 },
    ],
    confidence: "medium",
  }),
  MacroViewSchema: JSON.stringify({
    overallDirection: "mixed",
    summary:
      "수집된 데이터에서는 아동 도서에 대한 관심이 일관적으로 유지되었으나, 기술 친화적 콘텐츠 출시 시점에 강한 긍정 반응이 관찰되었다. 전반적으로 시장은 새로운 형식 실험에 호의적이다.",
    inflectionPoints: [
      { date: "2025-12-15", event: "Apache Kafka 일러스트북 공개", impact: "high" },
      { date: "2026-02-03", event: "Soviet 컬렉터 아이템 화제", impact: "medium" },
    ],
    dailyMentionTrend: [
      { date: "2025-12-15", count: 24, sentiment: "positive" },
      { date: "2026-02-03", count: 18, sentiment: "neutral" },
    ],
    confidence: "medium",
  }),
  SummarySchema: JSON.stringify({
    oneLiner: "기술 친화적 아동 도서가 출판 시장의 차세대 성장 축이다",
    keyTakeaways: [
      "기술-친화 형식에 대한 강한 긍정 반응 확인",
      "전통적 동화 vs 기술 친화 형식 사이의 프레임 경쟁 존재",
      "교육적 가치를 강조한 메시지가 수용도가 가장 높음",
    ],
    criticalActions: [
      { action: "기술 친화 아동 도서 라인업 사전 기획", priority: "high" },
      { action: "교육적 가치 중심의 마케팅 메시지 표준화", priority: "high" },
      { action: "전통주의 비판에 대한 대응 가이드 작성", priority: "medium" },
    ],
    confidence: "medium",
  }),
  IntegratedSchema: JSON.stringify({
    title: "EduRights SignalCraft — children's books 통합 리포트",
    sections: [
      {
        id: "section-1",
        title: "한 줄 요약 (BLUF)",
        content: "기술 친화적 아동 도서가 출판 시장의 차세대 성장 축이다.",
        sourceModule: "#08",
      },
      {
        id: "section-2",
        title: "여론 흐름",
        content:
          "수집된 데이터에서는 아동 도서에 대한 관심이 유지되었으며, 기술 친화 콘텐츠 출시 시점에 강한 긍정 반응이 관찰되었다. 변곡점은 2025-12-15(Kafka 일러스트북 공개)와 2026-02-03(Soviet 컬렉터 화제)이다.",
        sourceModule: "#01",
      },
      {
        id: "section-3",
        title: "감정 분포 & 키워드",
        content:
          "긍정 55%, 부정 20%, 중립 25%. 핵심 키워드: kafka(12), kids(9), education(6). 프레임 경쟁: '교육 vs 단순 동화'(60%), '기술 친화 vs 추상 위험'(40%).",
        sourceModule: "#03",
      },
      {
        id: "section-4",
        title: "즉시 실행 과제",
        content:
          "1) 기술 친화 아동 도서 라인업 사전 기획 (high)\n2) 교육적 가치 중심 마케팅 메시지 표준화 (high)\n3) 전통주의 비판 대응 가이드 작성 (medium)",
        sourceModule: "#08",
      },
    ],
    metadata: {
      keyword: KEYWORD,
      generatedAt: new Date().toISOString(),
      modulesUsed: ["#01", "#03", "#08"],
    },
    confidence: "medium",
    disclaimer: "Test fixture — generated by registerProvider, not by an LLM.",
  }),
};

const testProvider: LLMProvider = {
  name: "mock",
  async call(req: LLMRequest): Promise<LLMResponse> {
    const fixture = req.expectedSchemaName ? FIXTURES[req.expectedSchemaName] : null;
    if (!fixture) throw new Error(`No fixture for ${req.expectedSchemaName}`);
    const inputChars = req.messages.reduce((s, m) => s + m.content.length, 0);
    return {
      content: fixture,
      inputTokens: Math.ceil(inputChars / 4),
      outputTokens: Math.ceil(fixture.length / 4),
      cachedInputTokens: 0,
      stopReason: "end_turn",
      latencyMs: 5,
    };
  },
};
registerProvider(testProvider);

const pool = getPool();

const insert = await pool.query<{ id: string }>(
  `INSERT INTO signalcraft_jobs
     (tenant_id, keyword, regions, modules_requested, status, current_stage)
   VALUES ($1, $2, $3, $4, 'queued', 'stage1:queued')
   RETURNING id`,
  [TENANT, KEYWORD, [], ["#01", "#03", "#08", "#13"]],
);
const jobId = insert.rows[0]?.id;
if (!jobId) throw new Error("failed to create job");
console.log("created signalcraft job:", jobId);

const result = await runPipeline({
  jobId,
  tenantId: TENANT,
  keyword: KEYWORD,
  regions: [],
});
console.log("pipeline result:", result);

if (!result.reportId) throw new Error("no report was persisted");
const r = await pool.query<ReportRow>(
  `SELECT id, tenant_id, job_id, kind, title, sections, metadata, created_at
     FROM reports WHERE id = $1`,
  [result.reportId],
);
const report = r.rows[0];
if (!report) throw new Error("report row missing after persist");

console.log("--- report row ---");
console.log("  id:        ", report.id);
console.log("  kind:      ", report.kind);
console.log("  title:     ", report.title);
console.log("  sections:  ", report.sections.length, "items");
console.log("  metadata:  ", JSON.stringify(report.metadata).slice(0, 200));

console.log("--- HTML render (first 600 chars) ---");
const html = renderReportHtml(report);
console.log(html.slice(0, 600));
console.log(`(total: ${html.length} chars)`);

// Cleanup
await pool.query("DELETE FROM signalcraft_jobs WHERE id = $1", [jobId]);
await pool.query("DELETE FROM reports WHERE id = $1", [result.reportId]);
await pool.query("DELETE FROM llm_usage WHERE tenant_id = $1", [TENANT]);
await closePool();
console.log("DONE");
