import { registerProvider } from "../client.ts";
import type { LLMProvider, LLMRequest, LLMResponse } from "../types.ts";

/**
 * Development fixture provider.
 *
 * When the real Anthropic / Google SDK integrations are not yet wired
 * (Phase 4 W12+) we still want the SignalCraft pipeline to reach a
 * meaningful terminal state in staging / local dev. This module
 * registers a deterministic provider on both the `anthropic` and
 * `google` slots that returns canned JSON matching each module's Zod
 * schema by `expectedSchemaName`.
 *
 * Activation: apps/api/src/index.ts calls registerDevFixtureProviders()
 * at boot when ANTHROPIC_API_KEY is not set. Once real keys land, the
 * real providers take over and this module can be left installed for
 * offline / CI runs.
 */

const FIXTURES: Record<string, () => unknown> = {
  SentimentSchema: () => ({
    sentimentRatio: { positive: 0.55, negative: 0.2, neutral: 0.25 },
    topKeywords: [
      { term: "kids", count: 9, sentiment: "neutral" },
      { term: "education", count: 6, sentiment: "positive" },
      { term: "book", count: 5, sentiment: "neutral" },
    ],
    frameCompetition: [
      { label: "educational value vs entertainment", share: 0.6 },
      { label: "tech-forward vs traditional", share: 0.4 },
    ],
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  MacroViewSchema: () => ({
    overallDirection: "mixed",
    summary:
      "The development fixture provider returned a stable placeholder narrative that summarizes the public interest captured in the sampled posts. In production this field contains an LLM-authored analysis of the collected raw_posts ordered by time.",
    inflectionPoints: [
      {
        date: new Date().toISOString().slice(0, 10),
        event: "Baseline snapshot captured (dev fixture).",
        impact: "medium",
      },
    ],
    dailyMentionTrend: [
      {
        date: new Date().toISOString().slice(0, 10),
        count: 50,
        sentiment: "neutral",
      },
    ],
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  SummarySchema: () => ({
    oneLiner: "개발 환경 픽스처 — 실제 LLM 키 연결 전 기본 요약입니다.",
    keyTakeaways: [
      "dev-fixture provider is active — numbers below are illustrative, not real analysis.",
      "SignalCraft pipeline end-to-end plumbing is verified.",
      "Swap in Anthropic/Google SDK providers via registerProvider() to unlock real outputs.",
    ],
    criticalActions: [
      {
        action: "Register real Anthropic provider and set ANTHROPIC_API_KEY",
        priority: "high",
      },
      {
        action: "Review LLM cost dashboard once real calls are flowing",
        priority: "medium",
      },
      {
        action: "Schedule prompt review session for module #03 once data arrives",
        priority: "medium",
      },
    ],
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  SegmentationSchema: () => ({
    segments: [
      {
        label: "core",
        sizeShare: 0.35,
        cohesion: "high",
        signatureTraits: ["positive reviews", "repurchase"],
        representativeQuote: "My kid loves it, we use it daily. (dev fixture)",
        volumeEstimate: 5,
      },
      {
        label: "neutral",
        sizeShare: 0.4,
        cohesion: "medium",
        signatureTraits: ["comparison questions"],
        representativeQuote: "Is it better than X? (dev fixture)",
        volumeEstimate: 6,
      },
      {
        label: "critical",
        sizeShare: 0.25,
        cohesion: "medium",
        signatureTraits: ["price concern"],
        representativeQuote: "Too expensive. (dev fixture)",
        volumeEstimate: 4,
      },
    ],
    dominantSegment: "neutral",
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider.",
  }),
  TopicSchema: () => ({
    topics: [
      {
        topic: "Price-to-value discussion (dev fixture)",
        share: 0.3,
        stance: { supportive: 0.5, opposed: 0.3, observing: 0.2 },
        representativeQuotes: ["price debate placeholder"],
        keywords: ["price", "value"],
      },
      {
        topic: "Quality comparison (dev fixture)",
        share: 0.25,
        stance: { supportive: 0.6, opposed: 0.2, observing: 0.2 },
        representativeQuotes: ["quality placeholder"],
        keywords: ["quality"],
      },
      {
        topic: "Feature curiosity (dev fixture)",
        share: 0.2,
        stance: { supportive: 0.4, opposed: 0.1, observing: 0.5 },
        representativeQuotes: ["feature placeholder"],
        keywords: ["features"],
      },
    ],
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider.",
  }),
  RiskMapSchema: () => ({
    risks: [
      {
        label: "Price resistance spreading (dev fixture)",
        category: "price",
        dimensions: { ignition: 0.6, spreadability: 0.5, persistence: 0.7, impactScope: 0.5 },
        priorityScore: 0.575,
        evidence: ["baseline placeholder"],
        triggerConditions: ["daily negative posts > 10"],
        earlyWarningSignal: "Main cafe thread with price complaint.",
      },
      {
        label: "Competitor campaign (dev fixture)",
        category: "competitor",
        dimensions: { ignition: 0.4, spreadability: 0.5, persistence: 0.5, impactScope: 0.4 },
        priorityScore: 0.45,
        evidence: ["placeholder"],
        triggerConditions: ["competitor price cut announced"],
        earlyWarningSignal: "Competitor campaign teaser detected.",
      },
      {
        label: "Quality concern (dev fixture)",
        category: "quality",
        dimensions: { ignition: 0.3, spreadability: 0.3, persistence: 0.4, impactScope: 0.3 },
        priorityScore: 0.325,
        evidence: ["placeholder"],
        triggerConditions: ["3+ defect posts in a week"],
        earlyWarningSignal: "New defect reports.",
      },
    ],
    overallRiskLevel: "moderate",
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider.",
  }),
  PreferenceSchema: () => ({
    brands: [
      {
        brand: "Our brand (dev fixture)",
        isOurs: true,
        rawMentionShare: 0.38,
        biasAdjustedRange: { lower: 0.25, upper: 0.35 },
        biasFactors: ["platform bias", "recent campaign"],
      },
      {
        brand: "Competitor A (dev fixture)",
        isOurs: false,
        rawMentionShare: 0.42,
        biasAdjustedRange: { lower: 0.38, upper: 0.5 },
        biasFactors: ["long tenure"],
      },
    ],
    methodologyNote: "Dev-fixture placeholder methodology (bias adjustment disabled).",
    confidence: "low",
    disclaimer:
      "본 수치는 dev-fixture placeholder이며 실제 데이터가 아닙니다. 실제 LLM 키 연결 후 재실행하세요.",
  }),
  ContentGapSchema: () => ({
    plans: [
      {
        topic: "Comparison video (dev fixture)",
        format: "long_video",
        tone: "comparison",
        targetSegment: "neutral",
        keyMessage: "Value-for-money breakdown placeholder.",
        callToAction: "Try free sample",
        recommendedChannels: ["YouTube"],
        estimatedEffort: "high",
        estimatedImpact: "high",
        publishWindowDays: 21,
        successMetric: "avg watch time > 50%",
      },
      {
        topic: "Parent review series (dev fixture)",
        format: "short_video",
        tone: "emotional",
        targetSegment: "core",
        keyMessage: "Real family testimonial placeholder.",
        callToAction: "Share your story",
        recommendedChannels: ["Instagram"],
        estimatedEffort: "medium",
        estimatedImpact: "medium",
        publishWindowDays: 14,
        successMetric: "engagement rate > 5%",
      },
      {
        topic: "Pricing FAQ (dev fixture)",
        format: "faq",
        tone: "informational",
        targetSegment: "critical",
        keyMessage: "Addressing common price concerns.",
        callToAction: "Read more",
        recommendedChannels: ["Blog"],
        estimatedEffort: "low",
        estimatedImpact: "medium",
        publishWindowDays: 7,
        successMetric: "FAQ visits > 1000/mo",
      },
    ],
    editorialRhythm: "Weekly cadence, alternating long/short form (dev fixture).",
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider.",
  }),
  CrisisSchema: () => ({
    focalRisk: "Price resistance spreading (dev fixture)",
    scenarios: [
      {
        type: "spread",
        triggerCondition: "Main community feature (dev fixture)",
        probability: "medium",
        ssctStrategy: "diminishment",
        steps: [
          {
            timing: "T+0~6h",
            action: "Publish price-value FAQ",
            channel: "Official blog",
            expectedOutcome: "Reduce negative share",
          },
          {
            timing: "Day 1",
            action: "Engage influencers",
            channel: "Instagram",
            expectedOutcome: "Reframe narrative",
          },
          {
            timing: "Week 1",
            action: "Push bundle promo",
            channel: "Email",
            expectedOutcome: "Boost conversion",
          },
        ],
        keyMessage: "Long-term value placeholder message.",
        successIndicator: "Positive share recovers within 7 days.",
      },
      {
        type: "contain",
        triggerCondition: "Early detection via social listening",
        probability: "high",
        ssctStrategy: "diminishment",
        steps: [
          {
            timing: "T+0~2h",
            action: "Monitor keyword alerts",
            channel: "Internal dashboard",
            expectedOutcome: "Rapid detection",
          },
          {
            timing: "T+2~6h",
            action: "Prepared Q&A release",
            channel: "Website",
            expectedOutcome: "Frame control",
          },
          {
            timing: "Day 1",
            action: "Targeted outreach to key complainants",
            channel: "DM",
            expectedOutcome: "Reduce noise",
          },
        ],
        keyMessage: "We hear you placeholder.",
        successIndicator: "Complaint count halved within 48h.",
      },
      {
        type: "reverse",
        triggerCondition: "Strong advocate emerges",
        probability: "low",
        ssctStrategy: "reinforcement",
        steps: [
          {
            timing: "Week 1",
            action: "Amplify advocate content",
            channel: "Social",
            expectedOutcome: "Narrative shift",
          },
          {
            timing: "Week 2",
            action: "Launch positive proof campaign",
            channel: "YouTube",
            expectedOutcome: "Attract neutrals",
          },
          {
            timing: "Week 4",
            action: "Publish customer success stories",
            channel: "Blog",
            expectedOutcome: "Long-term trust",
          },
        ],
        keyMessage: "Our community speaks for us placeholder.",
        successIndicator: "Positive share > pre-crisis baseline.",
      },
    ],
    stakeholderMap: [
      {
        audience: "Existing customers",
        priority: "high",
        channel: "Email",
        message: "Clarification placeholder.",
      },
      {
        audience: "Prospective buyers",
        priority: "medium",
        channel: "Web",
        message: "Reassurance placeholder.",
      },
    ],
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider.",
  }),
  SuccessSimSchema: () => ({
    baselineProbability: 0.42,
    scenarios: [
      {
        label: "Aggressive comparison content (dev fixture)",
        description: "Placeholder description",
        probability: 0.62,
        expectedRoi: "strong_positive",
        keyAssumptions: ["Assumption placeholder A", "Assumption placeholder B"],
      },
      {
        label: "Status quo (dev fixture)",
        description: "Placeholder description",
        probability: 0.38,
        expectedRoi: "neutral",
        keyAssumptions: ["No new campaign"],
      },
      {
        label: "Crisis response failure (dev fixture)",
        description: "Placeholder description",
        probability: 0.2,
        expectedRoi: "negative",
        keyAssumptions: ["Negative sentiment doubles"],
      },
    ],
    bayesianEvidence: [
      {
        sourceModule: "#03",
        signal: "positive rate baseline",
        directionEffect: "neutral",
        weight: 0.2,
      },
      {
        sourceModule: "#06",
        signal: "content gaps detected",
        directionEffect: "raises",
        weight: 0.3,
      },
      {
        sourceModule: "#05",
        signal: "moderate risk level",
        directionEffect: "lowers",
        weight: 0.25,
      },
    ],
    topLevers: [
      {
        lever: "Content velocity (dev fixture)",
        sensitivity: 0.5,
        recommendedAction: "Publish 2 comparison videos in 14 days.",
      },
      {
        lever: "Price messaging clarity",
        sensitivity: 0.4,
        recommendedAction: "Release value breakdown within 7 days.",
      },
    ],
    confidence: "low",
    disclaimer: "본 확률은 dev-fixture placeholder이며 실제 의사결정 근거로 사용할 수 없습니다.",
  }),
  QaSchema: () => ({
    overallTrustScore: 0.72,
    trustLevel: "medium",
    findings: [
      {
        severity: "info",
        type: "disclaimer_missing",
        affectedModules: ["#03"],
        description: "dev-fixture 샘플 출력에는 일부 모듈 disclaimer가 생략됨.",
        suggestedAction: "실제 LLM 실행 시 자동 채워짐.",
      },
    ],
    numberMismatches: [],
    recommendedDisclaimers: ["본 리포트는 dev-fixture placeholder 결과가 일부 포함되어 있습니다."],
    summary:
      "dev-fixture provider로 생성된 QA 검증 — 경미한 정보성 findings 1건. 실제 LLM 키 연결 후 재검증 필요.",
  }),
  IntegratedSchema: () => ({
    title: "GoldenCheck SignalCraft — Dev Fixture Integrated Report",
    sections: [
      {
        id: "section-1",
        title: "한 줄 요약",
        content:
          "개발 환경 픽스처 provider가 전체 파이프라인 end-to-end 검증을 위해 사용 중입니다.",
        sourceModule: "#08",
      },
      {
        id: "section-2",
        title: "여론 흐름",
        content:
          "실제 데이터 분석 대신 고정된 placeholder 서사가 삽입되었습니다. Anthropic/Google SDK를 등록하면 이 섹션은 실제 분석으로 교체됩니다.",
        sourceModule: "#01",
      },
      {
        id: "section-3",
        title: "감정 분포",
        content: "긍정 55% / 부정 20% / 중립 25% (dev fixture, 실제 분석 아님).",
        sourceModule: "#03",
      },
      {
        id: "section-4",
        title: "즉시 실행 과제",
        content: "1) Anthropic API 키 등록 (high)\n2) 실제 LLM 호출 비용 모니터링 활성화 (medium)",
        sourceModule: "#08",
      },
    ],
    metadata: {
      keyword: "(from context)",
      generatedAt: new Date().toISOString(),
      modulesUsed: ["#01", "#03", "#08"],
    },
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider — not suitable for production decisions.",
  }),
};

function devFixtureCall(req: LLMRequest): Promise<LLMResponse> {
  const schemaName = req.expectedSchemaName ?? "";
  const builder = FIXTURES[schemaName];
  if (!builder) {
    return Promise.reject(new Error(`dev-fixture: no fixture for schema "${schemaName}"`));
  }
  const fixture = builder();
  const content = JSON.stringify(fixture);
  const inputChars = req.messages.reduce((s, m) => s + m.content.length, 0);
  return Promise.resolve({
    content,
    inputTokens: Math.ceil(inputChars / 4),
    outputTokens: Math.ceil(content.length / 4),
    cachedInputTokens: 0,
    stopReason: "end_turn",
    latencyMs: 5,
  });
}

export function registerDevFixtureProviders(): void {
  const anthropic: LLMProvider = { name: "anthropic", call: devFixtureCall };
  const google: LLMProvider = { name: "google", call: devFixtureCall };
  registerProvider(anthropic);
  registerProvider(google);
}

// Side-effect auto-registration: when this module is imported for the first
// time, register unless a real Anthropic API key is present. Import from
// anywhere in the module tree (including the BullMQ worker path) is
// sufficient — we no longer rely on index.ts running registration for us.
if (!process.env.ANTHROPIC_API_KEY) {
  registerDevFixtureProviders();

  console.log(`[dev-fixture] self-registered at import (cwd=${process.cwd()})`);
}
