import { registerProvider } from "../client.ts";
import type { LLMProvider, LLMRequest, LLMResponse } from "../types.ts";

/**
 * Development fixture provider.
 *
 * When the real Anthropic / Google SDK integrations are not yet wired
 * (Phase 4 W12+) we still want the SignalCraft pipeline to reach a
 * meaningful terminal state in staging / local dev. This module
 * registers a deterministic provider on both the `anthropic` and
 * `google` slots that returns canned JSON matching each module's Zod
 * schema by `expectedSchemaName`.
 *
 * Activation: apps/api/src/index.ts calls registerDevFixtureProviders()
 * at boot when ANTHROPIC_API_KEY is not set. Once real keys land, the
 * real providers take over and this module can be left installed for
 * offline / CI runs.
 */

const FIXTURES: Record<string, () => unknown> = {
  SentimentSchema: () => ({
    sentimentRatio: { positive: 0.55, negative: 0.2, neutral: 0.25 },
    topKeywords: [
      { term: "kids", count: 9, sentiment: "neutral" },
      { term: "education", count: 6, sentiment: "positive" },
      { term: "book", count: 5, sentiment: "neutral" },
    ],
    frameCompetition: [
      { label: "educational value vs entertainment", share: 0.6 },
      { label: "tech-forward vs traditional", share: 0.4 },
    ],
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  MacroViewSchema: () => ({
    overallDirection: "mixed",
    summary:
      "The development fixture provider returned a stable placeholder narrative that summarizes the public interest captured in the sampled posts. In production this field contains an LLM-authored analysis of the collected raw_posts ordered by time.",
    inflectionPoints: [
      {
        date: new Date().toISOString().slice(0, 10),
        event: "Baseline snapshot captured (dev fixture).",
        impact: "medium",
      },
    ],
    dailyMentionTrend: [
      {
        date: new Date().toISOString().slice(0, 10),
        count: 50,
        sentiment: "neutral",
      },
    ],
    confidence: "medium",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  SummarySchema: () => ({
    oneLiner: "개발 환경 픽스처 — 실제 LLM 키 연결 전 기본 요약입니다.",
    keyTakeaways: [
      "dev-fixture provider is active — numbers below are illustrative, not real analysis.",
      "SignalCraft pipeline end-to-end plumbing is verified.",
      "Swap in Anthropic/Google SDK providers via registerProvider() to unlock real outputs.",
    ],
    criticalActions: [
      {
        action: "Register real Anthropic provider and set ANTHROPIC_API_KEY",
        priority: "high",
      },
      {
        action: "Review LLM cost dashboard once real calls are flowing",
        priority: "medium",
      },
      {
        action: "Schedule prompt review session for module #03 once data arrives",
        priority: "medium",
      },
    ],
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider — replace with real LLM keys for production.",
  }),
  IntegratedSchema: () => ({
    title: "EduRights SignalCraft — Dev Fixture Integrated Report",
    sections: [
      {
        id: "section-1",
        title: "한 줄 요약",
        content:
          "개발 환경 픽스처 provider가 전체 파이프라인 end-to-end 검증을 위해 사용 중입니다.",
        sourceModule: "#08",
      },
      {
        id: "section-2",
        title: "여론 흐름",
        content:
          "실제 데이터 분석 대신 고정된 placeholder 서사가 삽입되었습니다. Anthropic/Google SDK를 등록하면 이 섹션은 실제 분석으로 교체됩니다.",
        sourceModule: "#01",
      },
      {
        id: "section-3",
        title: "감정 분포",
        content: "긍정 55% / 부정 20% / 중립 25% (dev fixture, 실제 분석 아님).",
        sourceModule: "#03",
      },
      {
        id: "section-4",
        title: "즉시 실행 과제",
        content: "1) Anthropic API 키 등록 (high)\n2) 실제 LLM 호출 비용 모니터링 활성화 (medium)",
        sourceModule: "#08",
      },
    ],
    metadata: {
      keyword: "(from context)",
      generatedAt: new Date().toISOString(),
      modulesUsed: ["#01", "#03", "#08"],
    },
    confidence: "low",
    disclaimer: "Generated by dev-fixture provider — not suitable for production decisions.",
  }),
};

function devFixtureCall(req: LLMRequest): Promise<LLMResponse> {
  const schemaName = req.expectedSchemaName ?? "";
  const builder = FIXTURES[schemaName];
  if (!builder) {
    return Promise.reject(new Error(`dev-fixture: no fixture for schema "${schemaName}"`));
  }
  const fixture = builder();
  const content = JSON.stringify(fixture);
  const inputChars = req.messages.reduce((s, m) => s + m.content.length, 0);
  return Promise.resolve({
    content,
    inputTokens: Math.ceil(inputChars / 4),
    outputTokens: Math.ceil(content.length / 4),
    cachedInputTokens: 0,
    stopReason: "end_turn",
    latencyMs: 5,
  });
}

export function registerDevFixtureProviders(): void {
  const anthropic: LLMProvider = { name: "anthropic", call: devFixtureCall };
  const google: LLMProvider = { name: "google", call: devFixtureCall };
  registerProvider(anthropic);
  registerProvider(google);
}

// Side-effect auto-registration: when this module is imported for the first
// time, register unless a real Anthropic API key is present. Import from
// anywhere in the module tree (including the BullMQ worker path) is
// sufficient — we no longer rely on index.ts running registration for us.
if (!process.env.ANTHROPIC_API_KEY) {
  registerDevFixtureProviders();

  console.log(`[dev-fixture] self-registered at import (cwd=${process.cwd()})`);
}
